name: photoapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.4
  get: 4.6.1
  dio: ^4.0.4
  pretty_dio_logger: ^1.1.1
  pull_to_refresh: ^2.0.0

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.4
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

